namespace DoomNET;

// This enum is sourced from Microsoft's own virtual key-codes documentation.
// This is used to, a lot more easily, take user input
// Source:
// * https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
public enum VK : byte
{
	LBUTTON = 0x01, // Left mouse button
	RBUTTON = 0x02, // Right mouse button
	CANCEL = 0x03, // Control-break processing
	MBUTTON = 0x04, // Middle mouse button
	XBUTTON1 = 0x05, // X1 mouse button
	XBUTTON2 = 0x06, // X2 mouse button
	RESERVED1 = 0x07, // Reserved
	BACK = 0x08, // Backspace key
	TAB = 0x09, // Tab key
	RESERVED2 = 0x0A, // Reserved
	RESERVED3 = 0x0B, // Reserved
	CLEAR = 0x0C, // Clear key
	RETURN = 0x0D, // Enter key
	UNASSIGNED1 = 0x0E, // Unassigned
	UNASSIGNED2 = 0x0F, // Unassigned
	SHIFT = 0x10, // Shift key
	CONTROL = 0x11, // Ctrl key
	MENU = 0x12, // Alt key
	PAUSE = 0x13, // Pause key
	CAPITAL = 0x14, // Caps lock key
	KANA = 0x15, // IME Kana mode
	HANGUL = 0x15, // IME Hangul mode
	IME_ON = 0x16, // IME On
	JUNJA = 0x17, // IME Junja mode
	FINAL = 0x18, // IME final mode
	HANJA = 0x19, // IME Hanja mode
	KANJI = 0x19, // IME Kanji mode
	IME_OFF = 0x1A, // IME Off
	ESCAPE = 0x1B, // Escape key
	CONVERT = 0x1C, // IME convert
	NONCONVERT = 0x1D, // IME nonconvert
	ACCEPT = 0x1E, // IME accept
	MODECHANGE = 0x1F, // IME mode change request
	SPACE = 0x20, // Spacebar
	PRIOR = 0x21, // Page up key
	NEXT = 0x22, // Page down key
	END = 0x23, // End key
	HOME = 0x24, // Home key
	LEFT = 0x25, // Left arrow key
	UP = 0x26, // Up arrow key
	RIGHT = 0x27, // Right arrow key
	DOWN = 0x28, // Down arrow key
	SELECT = 0x29, // Select key
	PRINT = 0x2A, // Print key
	EXECUTE = 0x2B, // Execute key
	SNAPSHOT = 0x2C, // Print screen key
	INSERT = 0x2D, // Insert key
	DELETE = 0x2E, // Delete key
	HELP = 0x2F, // Help key
	ZERO = 0x30, // 0 key
	ONE = 0x31, // 1 key
	TWO = 0x32, // 2 key
	THREE = 0x33, // 3 key
	FOUR = 0x34, // 4 key
	FIVE = 0x35, // 5 key
	SIX = 0x36, // 6 key
	SEVEN = 0x37, // 7 key
	EIGHT = 0x38, // 8 key
	NINE = 0x39, // 9 key
	UNDEFINED1 = 0x3A, // Undefined
	UNDEFINED2 = 0x3B, // Undefined
	UNDEFINED3 = 0x3C, // Undefined
	UNDEFINED4 = 0x3D, // Undefined
	UNDEFINED5 = 0x3E, // Undefined
	UNDEFINED6 = 0x3F, // Undefined
	UNDEFINED7 = 0x40, // Undefined
	A = 0x41, // A key
	B = 0x42, // B key
	C = 0x43, // C key
	D = 0x44, // D key
	E = 0x45, // E key
	F = 0x46, // F key
	G = 0x47, // G key
	H = 0x48, // H key
	I = 0x49, // I key
	J = 0x4A, // J key
	K = 0x4B, // K key
	L = 0x4C, // L key
	M = 0x4D, // M key
	N = 0x4E, // N key
	O = 0x4F, // O key
	P = 0x50, // P key
	Q = 0x51, // Q key
	R = 0x52, // R key
	S = 0x53, // S key
	T = 0x54, // T key
	U = 0x55, // U key
	V = 0x56, // V key
	W = 0x57, // W key
	X = 0x58, // X key
	Y = 0x59, // Y key
	Z = 0x5A, // Z key
	LWIN = 0x5B, // Left Windows key
	RWIN = 0x5C, // Right Windows key
	APPS = 0x5D, // Applications key
	RESERVED4 = 0x5E, // Reserved
	SLEEP = 0x5F, // Computer Sleep key
	NUMPAD0 = 0x60, // Numeric keypad 0 key
	NUMPAD1 = 0x61, // Numeric keypad 1 key
	NUMPAD2 = 0x62, // Numeric keypad 2 key
	NUMPAD3 = 0x63, // Numeric keypad 3 key
	NUMPAD4 = 0x64, // Numeric keypad 4 key
	NUMPAD5 = 0x65, // Numeric keypad 5 key
	NUMPAD6 = 0x66, // Numeric keypad 6 key
	NUMPAD7 = 0x67, // Numeric keypad 7 key
	NUMPAD8 = 0x68, // Numeric keypad 8 key
	NUMPAD9 = 0x69, // Numeric keypad 9 key
	MULTIPLY = 0x6A, // Multiply key
	ADD = 0x6B, // Add key
	SEPARATOR = 0x6C, // Separator key
	SUBTRACT = 0x6D, // Subtract key
	DECIMAL = 0x6E, // Decimal key
	DIVIDE = 0x6F, // Divide key
	F1 = 0x70, // F1 key
	F2 = 0x71, // F2 key
	F3 = 0x72, // F3 key
	F4 = 0x73, // F4 key
	F5 = 0x74, // F5 key
	F6 = 0x75, // F6 key
	F7 = 0x76, // F7 key
	F8 = 0x77, // F8 key
	F9 = 0x78, // F9 key
	F10 = 0x79, // F10 key
	F11 = 0x7A, // F11 key
	F12 = 0x7B, // F12 key
	F13 = 0x7C, // F13 key
	F14 = 0x7D, // F14 key
	F15 = 0x7E, // F15 key
	F16 = 0x7F, // F16 key
	F17 = 0x80, // F17 key
	F18 = 0x81, // F18 key
	F19 = 0x82, // F19 key
	F20 = 0x83, // F20 key
	F21 = 0x84, // F21 key
	F22 = 0x85, // F22 key
	F23 = 0x86, // F23 key
	F24 = 0x87, // F24 key
	RESERVED5 = 0x88, // Reserved
	RESERVED6 = 0x89, // Reserved
	RESERVED7 = 0x8A, // Reserved
	RESERVED8 = 0x8B, // Reserved
	RESERVED9 = 0x8C, // Reserved
	RESERVED10 = 0x8D, // Reserved
	RESERVED11 = 0x8E, // Reserved
	RESERVED12 = 0x8F, // Reserved
	NUMLOCK = 0x90, // Num lock key
	SCROLL = 0x91, // Scroll lock key
	OEMSPECIFIC1 = 0x92, // OEM specific
	OEMSPECIFIC2 = 0x93, // OEM specific
	OEMSPECIFIC3 = 0x94, // OEM specific
	OEMSPECIFIC4 = 0x95, // OEM specific
	OEMSPECIFIC5 = 0x96, // OEM specific
	UNASSIGNED3 = 0x97, // Unassigned
	UNASSIGNED4 = 0x98, // Unassigned
	UNASSIGNED5 = 0x99, // Unassigned
	UNASSIGNED6 = 0x9A, // Unassigned
	UNASSIGNED7 = 0x9B, // Unassigned
	UNASSIGNED8 = 0x9C, // Unassigned
	UNASSIGNED9 = 0x9D, // Unassigned
	UNASSIGNED10 = 0x9E, // Unassigned
	UNASSIGNED11 = 0x9F, // Unassigned
	LSHIFT = 0xA0, // Left shift key
	RSHIFT = 0xA1, // Right shift key
	LCONTROL = 0xA2, // Left control key
	RCONTROL = 0xA3, // Right control key
	LMENU = 0xA4, // Left alt key
	RMENU = 0xA5, // Right alt key
	BROWSER_BACK = 0xA6, // Browser Back key
	BROWSER_FORWARD = 0xA7, // Browser Forward key
	BROWSER_REFRESH = 0xA8, // Browser Refresh key
	BROWSER_STOP = 0xA9, // Browser Stop key
	BROWSER_SEARCH = 0xAA, // Browser Search key
	BROWSER_FAVORITES = 0xAB, // Browser Favorites key
	BROWSER_HOME = 0xAC, // Browser Start and Home key
	VOLUME_MUTE = 0xAD, // Volume Mute key
	VOLUME_DOWN = 0xAE, // Volume Down key
	VOLUME_UP = 0xAF, // Volume Up key
	MEDIA_NEXT_TRACK = 0xB0, // Next Track key
	MEDIA_PREV_TRACK = 0xB1, // Previous Track key
	MEDIA_STOP = 0xB2, // Stop Media key
	MEDIA_PLAY_PAUSE = 0xB3, // Play/Pause Media key
	LAUNCH_MAIL = 0xB4, // Start Mail key
	LAUNCH_MEDIA_SELECT = 0xB5, // Select Media key
	LAUNCH_APP1 = 0xB6, // Start Application 1 key
	LAUNCH_APP2 = 0xB7, // Start Application 2 key
	RESERVED13 = 0xB8, // Reserved
	RESERVED14 = 0xB9, // Reserved
	OEM_1 = 0xBA, // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ;: key
	OEM_PLUS = 0xBB, // For any country/region, the + key
	OEM_COMMA = 0xBC, // For any country/region, the , key
	OEM_MINUS = 0xBD, // For any country/region, the - key
	OEM_PERIOD = 0xBE, // For any country/region, the . key
	OEM_2 = 0xBF, // Used for miscellaneous characters; it can vary by keyboard. For the Us standard keyboard, the /? key
	OEM_3 = 0xC0, // Used for miscellaneous characters; it can vary by keyboard. For the Us standard keyboard, the `~ key
	RESERVED15 = 0xC1, // Reserved
	RESERVED16 = 0xC2, // Reserved
	RESERVED17 = 0xC3, // Reserved
	RESERVED18 = 0xC4, // Reserved
	RESERVED19 = 0xC5, // Reserved
	RESERVED20 = 0xC6, // Reserved
	RESERVED21 = 0xC7, // Reserved
	RESERVED22 = 0xC8, // Reserved
	RESERVED23 = 0xC9, // Reserved
	RESERVED24 = 0xCA, // Reserved
	RESERVED25 = 0xCB, // Reserved
	RESERVED26 = 0xCC, // Reserved
	RESERVED27 = 0xCD, // Reserved
	RESERVED28 = 0xCE, // Reserved
	RESERVED29 = 0xCF, // Reserved
	RESERVED30 = 0xD0, // Reserved
	RESERVED31 = 0xD1, // Reserved
	RESERVED32 = 0xD2, // Reserved
	RESERVED33 = 0xD3, // Reserved
	RESERVED34 = 0xD4, // Reserved
	RESERVED35 = 0xD5, // Reserved
	RESERVED36 = 0xD6, // Reserved
	RESERVED37 = 0xD7, // Reserved
	RESERVED38 = 0xD8, // Reserved
	RESERVED39 = 0xD9, // Reserved
	RESERVED40 = 0xDA, // Reserved
	OEM_4 = 0xDB, // Used for miscellaneous characters; it can vary by keyboard. For the Us standard keyboard, the [{ key
	OEM_5 = 0xDC, // Used for miscellaneous characters; it can vary by keyboard. For the Us standard keyboard, the \| key
	OEM_6 = 0xDD, // Used for miscellaneous characters; it can vary by keyboard. For the Us standard keyboard, the ]} key
	OEM_7 = 0xDE, // Used for miscellaneous characters; it can vary by keyboard. For the Us standard keyboard, the '" key
	OEM_8 = 0xDF, // Used for miscellaneous characters; it can vary by keyboard.
	RESERVED41 = 0xE0, // Reserved
	OEM_SPECIFIC1 = 0xE1, // OEM specific
	OEM_102 = 0xE2, // The <> keys on the US standard keyboard, or the \| key on the non-US 102-key keyboard
	OEM_SPECIFIC2 = 0xE3, // OEM specific
	OEM_SPECIFIC3 = 0xE4, // OEM specific
	PROCESSKEY = 0xE5, // IME Process key
	OEM_SPECIFIC4 = 0xE6, // OEM specific
	PACKET = 0xE7, // Used to pass Unicode characters as if they were keystrokes. The PACKET key is the low word of a
	               // 32-bit Virtual Key value used for non-keyboard input methods. For more information, see Remark
	               // in KEYBDINPUT, SendInput, WM_KEYDOWN, and WM_KEYUP
	UNASSIGNED12 = 0xE8, // Unassigned
	OEM_SPECIFIC5 = 0xE9, // OEM specific
	OEM_SPECIFIC6 = 0xEA, // OEM specific
	OEM_SPECIFIC7 = 0xEB, // OEM specific
	OEM_SPECIFIC8 = 0xEC, // OEM specific
	OEM_SPECIFIC9 = 0xED, // OEM specific
	OEM_SPECIFIC10 = 0xEE, // OEM specific
	OEM_SPECIFIC11 = 0xEF, // OEM specific
	OEM_SPECIFIC12 = 0xF0, // OEM specific
	OEM_SPECIFIC13 = 0xF1, // OEM specific
	OEM_SPECIFIC14 = 0xF2, // OEM specific
	OEM_SPECIFIC15 = 0xF3, // OEM specific
	OEM_SPECIFIC16 = 0xF4, // OEM specific
	OEM_SPECIFIC17 = 0xF5, // OEM specific
	ATTN = 0xF6, // Attn key
	CRSEL = 0xF7, // CrSel key
	EXSEL = 0xF8, // ExSel key
	EREOF = 0xF9, // Erase EOF key
	PLAY = 0xFA, // Play key
	ZOOM = 0xFB, // Zoom key
	NONAME = 0xFC, // Reserved
	PA1 = 0xFD, // PA1 key
	OEM_CLEAR = 0xFE // Clear key
}