using System.Linq;
using System.Collections.Generic;

using DoomNET.Entities;
using DoomNET.Resources;

namespace DoomNET.WTF;

/// <summary>
/// WTF file, acronym for Where's The Files, describes all of the entities and brushes of a map
/// </summary>
public class WTFFile
{
    private List<(Entity entity, string id)> entities { get; set; } = new(); // List of entities (and their IDs) in this WTF file
    private List<Brush> brushes { get; set; } = new(); // All of the brushes in this WTF file

    public string filepath { get; set; } // The directory of which this WTF file is saved at

    /// <summary>
    /// Add an entity to the entities list
    /// </summary>
    /// <param name="entity">Input entity</param>
    /// <param name="id">Input ID, autogenerated if null</param>
    public void AddEntity(Entity entity, string id = null)
    {
        entities.Add((entity, id));
    }

    /// <summary>
    /// Add a brush to the list of this WTF file
    /// </summary>
    /// <param name="brush">The brush that we're to add to this file</param>
    public void AddBrush(Brush brush)
    {
        // Add the brush to the list
        brushes.Add(brush);
    }

    /// <summary>
    /// Remove a brush from the list of this WTF file
    /// </summary>
    /// <param name="brush">The brush that we're to remove from this file</param>
    public void RemoveBrush(Brush brush)
    {
        // Remove the brush from the list
        brushes.Remove(brush);
    }

    /// <summary>
    /// Remove the entity from the entities list
    /// </summary>
    /// <param name="entity">Desired entity to remove</param>
    /// <param name="id">ID of the entity we wish to remove</param>
    public void RemoveEntity(Entity entity, string id = null)
    {
        entities.Remove((entity, id));
    }

    public List<(Entity entities, string id)> GetEntities()
    {
        return entities;
    }

    /// <summary>
    /// Returns this file's list of brushes
    /// </summary>
    public List<Brush> GetBrushes()
    {
        return brushes;
    }

    /// <summary>
    /// Called when saving the file
    /// </summary>
    public void OnSave()
    {
        // For every entity, set their ID to i, 0 should always be the player
        for (int i = 0; i < entities.Count; i++)
        {
            // If the entity is null, continue
            if (entities[i].entity == null)
            {
                continue;
            }

            entities[i] = (entities[i].entity, $"{i}");
        }

        for (int i = 0; i < brushes.Count; i++)
        {
            //brushes.ElementAt(i).id = $"brush {i}";
        }
    }

    /// <summary>
    /// Finds an entity according to their ID
    /// </summary>
    /// <param name="id">A specific ID of an entity</param>
    /// <returns>The desired entity appropriate to the inputted ID</returns>
    public Entity FindEntity(string id)
    {
        // Get the id of every entity
        for (int i = 0; i < entities.Count; i++)
        {
            // If entities[i]'s ID fits with the input ID, return that entity
            if (entities[i].id == id)
            {
                return entities[i].entity;
            }
        }

        // We didn't find an entity with that ID! Return null
        return null;
    }
}